@startuml
class logic.Message {
- String text
- User sender
+ String getText()
+ void setText(String)
+ User getSender()
+ void setSender(User)
}


class logic.User {
- String name
- String status
- ArrayList<Server> joinedServersList
+ boolean equals(Object)
+ void addJoinedServersList(Server)
+ void setStatus(String)
+ void setName(String)
+ String getName()
+ String getStatus()
+ ArrayList<Server> getJoinedServersList()
}


class logic.Channel {
- String name
- ArrayList<Message> messageList
+ void addMessage(Message)
+ void setName(String)
+ int getMessageCount()
+ String getName()
+ ArrayList<Message> getMessageList()
}


class logic.Server {
- String name
- User owner
- ArrayList<Channel> channelList
- ArrayList<User> memberList
+ boolean isMemberInServer(User)
+ Channel addChannel(User,String)
+ User addUser(User)
+ boolean kickUser(User,User)
+ void setName(String)
+ String getName()
+ User getOwner()
+ ArrayList<Channel> getChannelList()
+ ArrayList<User> getMemberList()
}


enum logic.TemplateType {
+  BASIC
+  GAMING
+  STUDY
}

class main.DiscordMain {
- {static} Scanner sc
- {static} ArrayList<User> usersList
- {static} ArrayList<Server> serversList
- {static} User currentUser
- {static} Server currentServer
- {static} Channel currentChannel
+ {static} void main(String[])
- {static} void signUpMenu()
- {static} void logInMenu()
- {static} void UserMenu()
- {static} void changeUsernameMenu()
- {static} void changeDisplayStatusMenu()
- {static} void createNewServerMenu()
- {static} void joinNewServerMenu()
- {static} void chooseServerMenu()
- {static} void serverMainMenu()
- {static} void kickMemberMenu()
- {static} void createNewChannelMenu()
- {static} void displayServerMembers()
- {static} void enterChannelMenu()
- {static} void channelMainMenu()
- {static} void writeNewMessageMenu()
- {static} void displayChannelMessages()
- {static} boolean isInUsersList(User)
- {static} int getChoiceInput()
- {static} String getTextInput()
- {static} void printBlock()
- {static} void initializeProgram()
}


@enduml